#!/bin/bash  
#merges files and folders correspoding to two mates

PATH_TO_OUTPUT=$1
INDIVIDUALS_BASE_NAME=$2

mkdir -p $PATH_TO_OUTPUT/alleles/temp_$INDIVIDUALS_BASE_NAME

#copies contents of the two folders $INDIVIDUALS_NAME'_1' and $INDIVIDUALS_NAME'_2' to the same new folder $INDIVIDUALS_NAME and merges files with the same name (like '1-2*01.fastq')
#for loop only runs twice 
for READ_DIR in $(ls -d $PATH_TO_OUTPUT/alleles/$INDIVIDUALS_BASE_NAME*); do
	for ALLELE_FILE in $(ls $READ_DIR); do
		ALLELE_NAME="${ALLELE_FILE%%.*}"
		cat "$READ_DIR/$ALLELE_FILE" >> "$PATH_TO_OUTPUT/alleles/temp_$INDIVIDUALS_BASE_NAME/$ALLELE_NAME.fastq";
	done
done

for OLD_FILE in $(ls -d $PATH_TO_OUTPUT/alleles/$INDIVIDUALS_BASE_NAME*); do
	rm -r $OLD_FILE
done
mv $PATH_TO_OUTPUT/alleles/temp_$INDIVIDUALS_BASE_NAME $PATH_TO_OUTPUT/alleles/$INDIVIDUALS_BASE_NAME
