#!/bin/bash  
#merges files and folders correspoding to two mates

PATH_TO_OUTPUT=$1
INDIVIDUALS_BASE_NAME=$2

mkdir -p $PATH_TO_OUTPUT/alleles/temp_$INDIVIDUALS_BASE_NAME

#copies contents of the two folders $INDIVIDUALS_NAME'_1' and $INDIVIDUALS_NAME'_2' to the same new folder $INDIVIDUALS_NAME and merges files with the same name (like '1-2*01.fastq')
#for loop only runs twice 
for PATH_TO_FILE_IN_END_PAIR in "$PATH_TO_OUTPUT/alleles/$INDIVIDUALS_NAME*/"*;
do
	ALLELE_NAME="${PATH_TO_FILE_IN_END_PAIR##*/}"
	ALLELE_NAME="${ALLELE_NAME%%.*}"
	cat "$PATH_TO_FILE_IN_END_PAIR" >> $PATH_TO_OUTPUT/alleles/$INDIVIDUALS_BASE_NAME/$ALLELE_NAME.fastq";
done

rm -r "$PATH_TO_OUTPUT/alleles/$INDIVIDUALS_NAME*"
mv $PATH_TO_OUTPUT/alleles/temp_$INDIVIDUALS_BASE_NAME $PATH_TO_OUTPUT/alleles/t$INDIVIDUALS_BASE_NAME
