#!/bin/bash
#calls the python script filter_using_mates.py for each allele file

PATH_TO_OUTPUT=$1 	#name of folder for the project 
INDIVIDUALS_BASE_NAME=$2
OFFSET=$3
THRESHOLD=$4
EPSILON=$5

#remove the directory filtered_alleles 
if [ -d "$PATH_TO_OUTPUT/filtered_alleles/$INDIVIDUALS_BASE_NAME" ]; then
    rm -r "$PATH_TO_OUTPUT/filtered_alleles/$INDIVIDUALS_BASE_NAME"
fi

mkdir -p $PATH_TO_OUTPUT/filtered_alleles/$INDIVIDUALS_BASE_NAME

#for each fasta file corresponding to an allele, this for loop calls filter_using_mates.py on each
for PATH_TO_OLD_SEGMENT_FILE in $(ls $PATH_TO_OUTPUT/clustered_alleles/$INDIVIDUALS_BASE_NAME/*);
do
	ALLELE_NAME="${PATH_TO_OLD_SEGMENT_FILE##*/}"
	ALLELE_NAME="${ALLELE_NAME%%.*}"
	python code/filter_using_mates.py "$PATH_TO_OLD_SEGMENT_FILE" "$PATH_TO_OUTPUT/filtered_alleles/$INDIVIDUALS_BASE_NAME/$ALLELE_NAME.fastq" "$INDIVIDUALS_BASE_NAME" "$PATH_TO_OUTPUT" "$ALLELE_NAME" "$OFFSET" "$THRESHOLD" "$EPSILON" 
done
