#!/bin/bash
#filters out the 1st, 2st, 3rd, 8th, and 10th column of the bam files for each read, separating those that are first-in-pair and those that are second-in-pair

module load samtools

PATH_TO_OUTPUT=$1
PATH_TO_BAM_FILE=$2
INDIVIDUALS_NAME=$3

mkdir -p $PATH_TO_OUTPUT/mates_filtered_bam_info

end1="_1"
end2="_2"

#filters out data from reads that are the first mate (third bit = 1 indicates this)
samtools view $PATH_TO_BAM_FILE | sort -k 3,3 -k4,4n | perl -ane 'print "$F[0] $F[1] $F[3] $F[7] $F[9]\n" if ($F[1]&0x40)' > "$PATH_TO_OUTPUT/mates_filtered_bam_info/"$INDIVIDUALS_NAME$end2".txt"
#filters out data from reads that are the second mate (fourth bit = 1 indicates this)
samtools view $PATH_TO_BAM_FILE | sort -k 3,3 -k4,4n | perl -ane 'print "$F[0] $F[1] $F[3] $F[7] $F[9]\n" if ($F[1]&0x80)' > "$PATH_TO_OUTPUT/mates_filtered_bam_info/"$INDIVIDUALS_NAME$end1".txt"


