#!/bin/bash


PATH_TO_OUTPUT=$1 	#name of folder for the project 
INDIVIDUALS_NAME=$2
PATH_TO_INDIVIDUAL_BAM=$3
PAIRED=$4

#remove the fq_files directory if it already exists
if [ -d "$PATH_TO_OUTPUT/fq_files/$INDIVIDUALS_NAME" ]; then
	    rm -r "$PATH_TO_OUTPUT/fq_files/$INDIVIDUALS_NAME"
fi

mkdir -p $PATH_TO_OUTPUT/fq_files/$INDIVIDUALS_NAME

#run bam2fastq to convert the bam file to fastq files
#will produce 3 fastq files, one for unpaired reads, and 2 for paired reads, one for each mate
./support_files/bamUtil/bin/bam bam2fastq --in $PATH_TO_INDIVIDUAL_BAM --unpairedOut "$PATH_TO_OUTPUT/fq_files/$INDIVIDUALS_NAME/$INDIVIDUALS_NAME.fq" --firstOut $PATH_TO_OUTPUT/fq_files/$INDIVIDUALS_NAME/$INDIVIDUALS_NAME"_1.fq" --secondOut $PATH_TO_OUTPUT/fq_files/$INDIVIDUALS_NAME/$INDIVIDUALS_NAME"_2.fq"


if [ $PAIRED = 'y' ] ; then 		#delete the unpaired read fastq if the user specified that it's paired reads
	rm "$PATH_TO_OUTPUT/fq_files/$INDIVIDUALS_NAME/$INDIVIDUALS_NAME.fq"
else		#delete the paired read fastq if the user specified that it's unpaired reads
	rm $PATH_TO_OUTPUT/fq_files/$INDIVIDUALS_NAME/$INDIVIDUALS_NAME"_1.fq"
	rm $PATH_TO_OUTPUT/fq_files/$INDIVIDUALS_NAME/$INDIVIDUALS_NAME"_2.fq"
fi

