from __future__ import print_function
from Bio import SeqIO
import os
import sys
import inspect
import importlib

# take all the contig files generated by de novo assembly and rename sequence
# according to segment name



def rename(contig_dir):
	contig_list=[] # initialize list of contigs
	for f in os.listdir(contig_dir):
		if f.split('.')[-1]=='fasta': # for each fasta file in contig directory
			seg_name = f.split('.')[0] # segment name is the filename (excluding extension)
			count=1 # sometimes there are multiple contigs, so keep track of this
			with open(contig_dir+f, 'r') as fin:
				for rec in SeqIO.parse(fin, 'fasta'):
					cov=rec.id.split('_')[5] # extract coverage info (6th field in seq id in spades output)
					# print(rec.id)
					contig_list.append(['>'+seg_name+'_cov_'+cov+'_contig_'+str(count), str(rec.seq)])
					count+=1

	with open(contig_dir+'all_contigs.fasta', 'w') as fout:
		for row in contig_list:
			print(row[0], row[1], sep='\n', end='\n', file=fout)

if __name__ == "__main__":
    dirname=sys.argv[1] # only argument should be the directory which stores all the contigs
    rename(dirname)

